-- Add anti-blocking protection fields to marketing_settings
ALTER TABLE public.marketing_settings
ADD COLUMN IF NOT EXISTS min_delay_seconds INTEGER NOT NULL DEFAULT 8,
ADD COLUMN IF NOT EXISTS max_delay_seconds INTEGER NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS daily_limit INTEGER NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS warmup_enabled BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS warmup_day INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS pause_every_n_messages INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS pause_duration_seconds INTEGER NOT NULL DEFAULT 30,
ADD COLUMN IF NOT EXISTS allowed_start_hour INTEGER NOT NULL DEFAULT 8,
ADD COLUMN IF NOT EXISTS allowed_end_hour INTEGER NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS messages_sent_today INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_reset_date DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS consecutive_errors INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_consecutive_errors INTEGER NOT NULL DEFAULT 3;